name: Build and Publish Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # 2. Log in to GitHub Docker Registry
      - name: Log in to GitHub Docker Registry
        run: echo "${{ secrets.GH_TOKEN }}" | docker login ghcr.io -u ${{ secrets.GH_AORDONEZ24 }} --password-stdin

      # 3. Build the Docker image
      - name: Build Docker image
        run: |
          docker build -t ghcr.io/${{ secrets.GH_AORDONEZ24 }}/ProyectoCC-24-25:latest .

      # 4. Push the Docker image to GitHub Packages
      - name: Push Docker image to GitHub Packages
        run: |
          docker push ghcr.io/${{ secrets.GH_AORDONEZ24 }}/ProyectoCC-24-25:latest
